### PR TITLE
[JENKINS-70906] Remove PrototypeJS Ajax.Updater

### PR DESCRIPTION
**Pull request by hashar**
The table of content in the sidebar would not show in the sidebar due to the removal of PrototypeJS in Jenkins 2.426.1. Replace the old Ajax.Updater call with a modern fetch().

I have confirmed the fix using `mvn hpi:run` with Jenkins 2.426.1 (and bumping the parent pom to 4.77).

### CODE REVIEW

**Comment by hashar** [comment]
This needs #25 to be merged first.

**Comment by mPokornyETM** [comment]
May you pls post here a screen shot, that this changes really works. This plugin have only few automated tests (and very less code coverage :-( )

thx

**Comment by hashar** [comment]
I wanted to cover the fix with an HtmlUnit test but unfortunately I could not quite figure out how to inject the plugin configuration (which on disk result in `work/org.jvnet.hudson.plugins.collapsingconsolesections.CollapsingSectionNote.xml`).

**Comment by mPokornyETM** [comment]
LGTM

**Pull request merged**
